/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xuetang9_kenny_Sample */

#ifndef _Included_com_xuetang9_kenny_Sample
#define _Included_com_xuetang9_kenny_Sample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xuetang9_kenny_Sample
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xuetang9_kenny_Sample_intMethod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
